name: "Deploy"

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/*.gitignore"
      - "**/*.gitattributes"
  workflow_dispatch:
    branches:
      - master

jobs:
  deploy:
    name: "Deploy React Application"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v5

      - name: "Set up Node"
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: "Install Dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build
        env:
          REACT_APP_API_URL: ""
          REACT_APP_GITHUB_API_URL: "https://api.github.com"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: rm -rf /var/www/portfolio/*

      - name: "Copy Files"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./build/*"
          target: "/var/www/tictactoe/client"
          strip_components: 1
